spring:

  datasource:
    url: jdbc:postgresql://localhost:1234/biteplate
    username: postgres
    password: Kama@12345

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest